<?xml version="1.0" ?>
<definitions name="sample2" targetNamespace="urn:sample2" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="urn:sample2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns="http://schemas.xmlsoap.org/wsdl/">
<types xmlns="http://schemas.xmlsoap.org/wsdl/" />
    <portType name="sample2Port">
        <operation name="HelloWorld">
            <input message="tns:HelloWorldRequest" />
            <output message="tns:HelloWorldResponse" />
        </operation>
    </portType>
    <binding name="sample2Binding" type="tns:sample2Port">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http" />
        <operation name="HelloWorld">
            <soap:operation soapAction="urn:sample2#SERVER#HelloWorld" />
            <input><soap:body use="encoded"
                              namespace="urn:sample2" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </input>
            <output>
                <soap:body use="encoded" namespace="urn:sample2" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" />
            </output>
        </operation>
    </binding>
    <service name="sample2">
        <documentation />
        <port name="sample2Port" binding="tns:sample2Binding">
            <soap:address location="http://admindev.com/wbs.php" />
        </port>
    </service>

    <message name="HelloWorldRequest"></message>
    <message name="HelloWorldResponse">
      <part name="HelloWorld" type="xsd:string" />
    </message>
</definitions>